/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preserve that ability, always export from Quest to regenerate this file.
 *   To setup element attributes and CSS properties, use the Quest web app
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import { styled } from "@mui/material";
import React from "react";
// import { styled } from "@mui/material/styles";
import TableItem2 from "src/components/TableItem2/TableItem2";

const Property1Default = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  width: "100%",
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
  height: "auto",
  minWidth: "785px",
});

const Header = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `36px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Name = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  flex: `1`,
  margin: `0px`,
});

const Name1 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  // color: theme.palette["Text"]["Disabled"],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Position = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `153.2px`,
  margin: `0px 0px 0px 12px`,
});

const Position1 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  // color: theme.palette["Text"]["Disabled"],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Contact = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `200px`,
  margin: `0px 0px 0px 12px`,
});

const EllenchoQuestAi = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  // color: theme.palette["Text"]["Disabled"],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Role = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `80px`,
  margin: `0px 0px 0px 12px`,
});

const EllenchoQuestAi1 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  // color: theme.palette["Text"]["Disabled"],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Role1 = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `90px`,
  margin: `0px 0px 0px 12px`,
});

const EllenchoQuestAi2 = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  // color: theme.palette["Text"]["Disabled"],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  lineHeight: `16px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Fpo = styled("div")(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  fontSynthesis: `none`,
  // color: theme.palette["Text"]["Disabled"],
  fontStyle: `normal`,
  fontFamily: `Heebo`,
  fontWeight: `400`,
  fontSize: `14px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  opacity: `0`,
  width: `26px`,
  margin: `0px 0px 0px 12px`,
}));

const Rows = styled("div")({
  borderRadius: `0px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const TableItem21 = styled(TableItem2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `64px`,
  margin: `0px`,
}));

const TableItem22 = styled(TableItem2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `64px`,
  margin: `0px`,
}));

const TableItem23 = styled(TableItem2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `64px`,
  margin: `0px`,
}));

const TableItem24 = styled(TableItem2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `64px`,
  margin: `0px`,
}));

function Table2() {
  return (
    <>
      <Property1Default
      // className={props.className}
      >
        <Header>
          <Name>
            <Name1>{`Name`}</Name1>
          </Name>
          <Position>
            <Position1>{`Position`}</Position1>
          </Position>
          <Contact>
            <EllenchoQuestAi>{`Contact`}</EllenchoQuestAi>
          </Contact>
          <Role>
            <EllenchoQuestAi1>{`Role`}</EllenchoQuestAi1>
          </Role>
          <Role1>
            <EllenchoQuestAi2>{`Status`}</EllenchoQuestAi2>
          </Role1>
          <Fpo>{`Edit`}</Fpo>
        </Header>
        <Rows>
          <TableItem21 />
          <TableItem22 />
          <TableItem23 />
          <TableItem24 />
        </Rows>
      </Property1Default>
    </>
  );
}

export default Table2;
